<a href="https://colab.research.google.com/github/Srideep-Kundu/MLProjects/blob/main/LogisticRegressionFromScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing dependencies
import numpy as np

In [39]:
class LogisticRegression():
  #initiating the parameters (learning rate and number of iterations)
  def __init__(self, alpha, epochs):
    self.alpha = alpha
    self.epochs = epochs
  def fit(self, X, Y):
    #number of training examples and number of features
    self.m, self.n = X.shape

    #initiating the weights and bias
    self.w = np.zeros(self.n)
    self.b = 0
    self.X = X
    self.Y = Y

    #implementing gradient descent
    for i in range(self.epochs):
      self.update_weights()

  def update_weights(self):
    Y_prediction = 1 / (1 + np.exp(-np.dot(self.X, self.w) + self.b))

    #calculate the gradients

    dw = (1 / self.m) * np.dot(self.X.T, (Y_prediction - self.Y))
    db = (1 / self.m) * np.sum(Y_prediction - self.Y)

    #update the weights
    self.w = self.w - self.alpha * dw
    self.b = self.b - self.alpha * db

  def predict(self, X):
    Y_pred = (1 / (1 + np.exp(-np.dot(X, self.w) + self.b)))
    Y_pred = np.where(Y_pred > 0.5, 1, 0)
    return Y_pred

In [40]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

###Data Collection and Analysis

In [41]:
diabetes_df = pd.read_csv('/content/diabetes (1).csv')

In [42]:
diabetes_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [43]:
diabetes_df.shape

(768, 9)

In [44]:
diabetes_df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [45]:
diabetes_df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [58]:
positive = diabetes_df[diabetes_df['Outcome'] == 1]
negative = diabetes_df[diabetes_df['Outcome'] == 0]

In [59]:
negative_sample = negative.sample(n=268)

In [61]:
diabetes_df = pd.concat([positive, negative_sample])
diabetes_df['Outcome'].value_counts()

Outcome
1    268
0    268
Name: count, dtype: int64

In [62]:
diabetes_df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000
mean,4.001866,125.477612,69.154851,20.591418,83.651119,32.517724,0.498440,33.729478,0.500000
std,3.499265,33.259549,19.962589,16.075030,119.720217,8.015243,0.336727,11.488944,0.500467
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.085000,21.000000,0.000000
25%,1.000000,102.000000,64.000000,0.000000,0.000000,27.700000,0.257750,24.000000,0.000000
50%,3.000000,122.000000,72.000000,23.000000,20.500000,32.450000,0.402000,30.000000,0.500000
75%,6.250000,147.000000,80.000000,32.000000,130.000000,36.800000,0.660250,41.000000,1.000000
max,17.000000,199.000000,114.000000,99.000000,846.000000,67.100000,2.420000,72.000000,1.000000

In [63]:
features = diabetes_df.drop(columns='Outcome', axis=1)
target = diabetes_df['Outcome']

In [64]:
print(features)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
2              8      183             64              0        0  23.3
4              0      137             40             35      168  43.1
6              3       78             50             32       88  31.0
8              2      197             70             45      543  30.5
..           ...      ...            ...            ...      ...   ...
660           10      162             84              0        0  27.7
434            1       90             68              8        0  24.5
632            2      111             60              0        0  26.2
81             2       74              0              0        0   0.0
350            4       92             80              0        0  42.2

     DiabetesPedigreeFunction  Age
0                       0.627   50
2                       0.672   32
4                       2.288   33
6                       0.248   26
8                       0.158   53
..                        ...  ...
660                     0.182   54
434                     1.138   36
632                     0.343   23
81                      0.102   22
350                     0.237   29

[536 rows x 8 columns]

In [65]:
print(target)

0      1
2      1
4      1
6      1
8      1
      ..
660    0
434    0
632    0
81     0
350    0
Name: Outcome, Length: 536, dtype: int64

In [66]:
X_train, X_test, Y_train, Y_test = train_test_split(features, target, test_size=0.2, random_state=2)

In [67]:
print(X_train.shape, X_test.shape)

(428, 8) (108, 8)

In [68]:
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [69]:
X_train.std()

np.float64(1.0)

In [70]:
X_test.std()

np.float64(0.9708168241728674)

###Training the model

In [71]:
model = LogisticRegression(alpha=0.01, epochs=1000)
model.fit(X_train, Y_train)

In [72]:
training_prediction = model.predict(X_train)
training_accuracy = accuracy_score(training_prediction, Y_train)

In [74]:
print('Accuracy on training data: ', training_accuracy)

Accuracy on training data:  0.7616822429906542

In [75]:
test_prediction = model.predict(X_test)
test_accuracy = accuracy_score(test_prediction, Y_test)

In [76]:
print('Accuracy on test data: ', test_accuracy)

Accuracy on test data:  0.75

###Making a predictive system

In [78]:
input_data = (0,113,76,0,0,33.3,0.278,23)  #Original outcome is 1
np_array = np.asarray(input_data)
input_data_reshaped = np_array.reshape(1, -1)
prediction = model.predict(input_data_reshaped)
print(prediction)
if prediction[0] == 0:
  print('The person is not diabetic')
else:
  print('The person is diabetic')

[1]
The person is diabetic