<a href="https://colab.research.google.com/github/Srideep-Kundu/MLProjects/blob/main/RegularizedLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [104]:
# Importing dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

##Creating Ridge Regression class

In [121]:
class L2_Regression():
  def __init__(self, alpha, epochs, lambda_parameter):
    self.alpha = alpha
    self.epochs = epochs
    self.lambda_parameter = lambda_parameter

  def fit(self, X, Y):
    self.m, self.n = X.shape

    self.w = np.zeros(self.n)
    self.b = 0

    self.X = X
    self.Y = Y

    #Implementing Gradient Descent
    for i in range(self.epochs):
      self.update_weights()

  def update_weights(self):
    Y_prediction = self.predict(self.X)

    #calculate gradients
    dw = 1/self.m * np.dot(self.X.T, (Y_prediction - self.Y)) - np.dot((self.lambda_parameter/self.m), self.w)
    db = 1/self.m * np.sum(Y_prediction - self.Y)

    #updating the weights

    self.w = self.w - self.alpha * dw
    self.b = self.b - self.alpha * db


  def predict(self, X):
    return np.dot(X, self.w) + self.b

###Brief Data Analysis

In [122]:
housing_df = pd.read_csv('/content/BostonHousing.csv')
housing_df.head()

      crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  price
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98   24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14   21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03   34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94   33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33   36.2

[5 rows x 14 columns]

In [123]:
housing_df.shape

(506, 14)

In [124]:
housing_df.describe()

             crim          zn       indus  ...           b       lstat       price
count  506.000000  506.000000  506.000000  ...  506.000000  506.000000  506.000000
mean     3.613524   11.363636   11.136779  ...  356.674032   12.653063   22.532806
std      8.601545   23.322453    6.860353  ...   91.294864    7.141062    9.197104
min      0.006320    0.000000    0.460000  ...    0.320000    1.730000    5.000000
25%      0.082045    0.000000    5.190000  ...  375.377500    6.950000   17.025000
50%      0.256510    0.000000    9.690000  ...  391.440000   11.360000   21.200000
75%      3.677083   12.500000   18.100000  ...  396.225000   16.955000   25.000000
max     88.976200  100.000000   27.740000  ...  396.900000   37.970000   50.000000

[8 rows x 14 columns]

In [125]:
housing_df.isnull().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
price      0
dtype: int64

In [126]:
X = housing_df.drop('price', axis=1)
Y = housing_df['price']

###Splitting the data into training and test data

In [127]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [128]:
print(X_train.shape, X_test.shape)

(404, 13) (102, 13)

###Standardising the data

In [129]:
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [130]:
X_train.std()

np.float64(1.0)

In [131]:
X_test.std()

np.float64(1.0326187959666866)

###Training our model

In [133]:
model = L2_Regression(alpha=0.001, epochs=100000, lambda_parameter=0.01)
model.fit(X_train, Y_train)

In [148]:
from sklearn.metrics import mean_squared_error, r2_score

X_train_prediction = model.predict(X_train)
train_mse = mean_squared_error(Y_train, X_train_prediction)
train_r2 = r2_score(Y_train, X_train_prediction)

print(f"Training Mean Squared Error: {train_mse}")
print(f"Training R2 Score: {train_r2}")

Training Mean Squared Error: 22.953693774186473
Training R2 Score: 0.7285831753184304

In [147]:
X_test_prediction = model.predict(X_test)
test_mse = mean_squared_error(Y_test, X_test_prediction)
test_r2 = r2_score(Y_test, X_test_prediction)

print(f"Training Mean Squared Error: {test_mse}")
print(f"Training R2 Score: {test_r2}")

Training Mean Squared Error: 18.495636140956545
Training R2 Score: 0.7789181630713576

###Making a prediction system

In [149]:
input_data = (0.62739,0,8.14,0,0.538,5.834,56.5,4.4986,4,307,21,395.62,8.47) # Original Price : $19.9k
nparray = np.asarray(input_data)
reshaped = nparray.reshape(1,-1)
std_data = scalar.transform(reshaped)
prediction = model.predict(std_data)
print(f"Original price: $19.9k")
print(f"Predicted price: ${prediction[0]:.1f}k")

Original price: $19.9k
Predicted price: $19.4k

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(